spring:
  application:
    name: abcm-voterId-api
  profiles:
    active: prod
  config:
     import: 
          - "classpath:/response-massage.yml"
          - "classpath:/application-email-config.yml"
