email.send.from: noreply@abcmapp.com
email.send.to: support@ablepay.in 
#support@ablepay.in 
email.send.bcc: support@abcmapp.com,krushna.dakale@abcmapp.dev
#support@abcmapp.com


email.lowBalance.template.path: /opt/tomcat/webapps/view-kyc/WEB-INF/classes/static/e-KYCEmailTemplate/eKyc-lowallet-balance.html
#C://KYCGIT//abcm-kyc-service-ui//src//main//resources//static//e-KYCEmailTemplate//eKyc-lowallet-balance.html
#/opt/apache-tomcat-10.1.28_ablepay/webapps/abcm-adhar-api/WEB-INF/classes/static/e-KYCEmailTemplate/eKyc-lowallet-balance.html
#C://KYCGIT//abcm-aadhaar-api//src//main//resources//static//e-KYCEmailTemplate//eKyc-lowallet-balance.html
email.send.api.url: https://enotification.chatnpay.com/email/withmailer/sendEmailWithAttachmentWithCc
email.lowbalance.subject: Low Wallet Balance â€“ Urgent Action Required to Avoid Service Disruption



#Ekyc Configuration
merchantId: K10001
ApiKey: 2SOMEO-YDUDNR-7AAMKS-L0L322
AppId: 6dd275b6809740028a31a458 

#Local
#EsignApi: http://localhost:8049/api/v1/eSignAadhaar/verify

#UAT
EsignApi: http://203.192.228.125:1002/abcm-esign-api/api/v1/eSignAadhaar/verify




#Esign Webhook

#Local
#webhookUrl: http://localhost:8087/esign/webhook

#UAT
webhookUrl: http://203.192.228.125:1002/view-kyc/esign/webhook
