spring:
  datasource:
    url: jdbc:mysql://wnpay-prd.cayouse6wadz.ap-south-1.rds.amazonaws.com:3306/abcm_kyc_ms_db?createDatabaseIfNotExist=true&useSSL=true&useUnicode=yes&characterEncoding=UTF-8
    username: wnpayadmin
    password: AbcmWnpayRds2022
    driver-class-name: com.mysql.cj.jdbc.Driver  # Explicitly define the driver class name
  jpa:
    hibernate:
      ddl-auto: update
        # Removed dialect property
    show-sql: false
ContextPath: https://ekyc.ablepay.in/view-kyc


server:
  port: 8087

logging:
  level:
    root: INFO


apiKey : 9a447a58-2f26-49d5-9421-383ac14b3a24
salt : 788bcd8b464c024453a1ca4c7bc8260292210ea5
ablePayUrl : https://pgbiz.ablepay.co.in/v2/paymentrequest
statusApi: https://pgbiz.ablepay.co.in/v2/paymentstatus 
returnUrl: https://ekyc.ablepay.in/view-kyc/payment-response
environment: LIVE
LogFilepath: /home/ekyc-log/view-kyc-log/



management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    health:
      show-details: always
prometheus:
 metrics:
 export:
 enabled: true

 
 spring.jpa.properties.hibernate.format_sql: true